version: "3.8"

services:
  app:
    container_name: app_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
